Fix unit tests
Fix unit tests to work after be5a3c8 commit. Subsequent to that change
the following unit tests errors were occurring due to a change in how
the cache was used.

    Error in test testGetLastValue (ZenPacks.zenoss.CalculatedPerformance.tests.testRRDReadThroughCache.TestRRDReadThroughCache)
    Traceback (most recent call last):
      File "/usr/lib64/python2.7/unittest/case.py", line 369, in run
        testMethod()
      File "/mnt/src/ZenPacks.zenoss.CalculatedPerformance/ZenPacks/zenoss/CalculatedPerformance/tests/testRRDReadThroughCache.py", line 55, in testGetLastValue
        'ds', 'dp', 'rra', False, 1, {'rrdpath': 'perf/path', 'uuid': 1})[0][0],
    TypeError: 'float' object has no attribute '__getitem__'

    Error in test testGetLastValues (ZenPacks.zenoss.CalculatedPerformance.tests.testRRDReadThroughCache.TestRRDReadThroughCache)
    Traceback (most recent call last):
      File "/usr/lib64/python2.7/unittest/case.py", line 369, in run
        testMethod()
      File "/mnt/src/ZenPacks.zenoss.CalculatedPerformance/ZenPacks/zenoss/CalculatedPerformance/tests/testRRDReadThroughCache.py", line 78, in testGetLastValues
        {k: v[0][0] for k, v in expectedValues.iteritems()},
      File "/mnt/src/ZenPacks.zenoss.CalculatedPerformance/ZenPacks/zenoss/CalculatedPerformance/tests/testRRDReadThroughCache.py", line 78, in <dictcomp>
        {k: v[0][0] for k, v in expectedValues.iteritems()},
    TypeError: 'float' object has no attribute '__getitem__'

    Error in test testInvalidate (ZenPacks.zenoss.CalculatedPerformance.tests.testRRDReadThroughCache.TestRRDReadThroughCache)
    Traceback (most recent call last):
      File "/usr/lib64/python2.7/unittest/case.py", line 369, in run
        testMethod()
      File "/mnt/src/ZenPacks.zenoss.CalculatedPerformance/ZenPacks/zenoss/CalculatedPerformance/tests/testRRDReadThroughCache.py", line 113, in testInvalidate
        'ds', 'dp', 'rra', False, 1, {'rrdpath': 'perf/path', 'uuid': 1})[0][0],
    TypeError: 'float' object has no attribute '__getitem__'

    Error in test testPut (ZenPacks.zenoss.CalculatedPerformance.tests.testRRDReadThroughCache.TestRRDReadThroughCache)
    Traceback (most recent call last):
      File "/usr/lib64/python2.7/unittest/case.py", line 369, in run
        testMethod()
      File "/mnt/src/ZenPacks.zenoss.CalculatedPerformance/ZenPacks/zenoss/CalculatedPerformance/tests/testRRDReadThroughCache.py", line 45, in testPut
        'ds', 'dp', 'rra', False, 1, {'rrdpath': 'perf/path', 'uuid': 1})[0],
    TypeError: 'float' object has no attribute '__getitem__'

      Ran 28 tests with 0 failures and 4 errors in 24.891 seconds.

    Tests with errors:
       testGetLastValue (ZenPacks.zenoss.CalculatedPerformance.tests.testRRDReadThroughCache.TestRRDReadThroughCache)
       testGetLastValues (ZenPacks.zenoss.CalculatedPerformance.tests.testRRDReadThroughCache.TestRRDReadThroughCache)
       testInvalidate (ZenPacks.zenoss.CalculatedPerformance.tests.testRRDReadThroughCache.TestRRDReadThroughCache)
       testPut (ZenPacks.zenoss.CalculatedPerformance.tests.testRRDReadThroughCache.TestRRDReadThroughCache)